#+TITLE: Other Papers


* TODO Advances in Computational Studies of Potential Drug Targets in Mycobacterium tuberculosis.
https://www.ncbi.nlm.nih.gov/pubmed/30084331
* TODO Hybrid design of isonicotinic acid hydrazide derivatives: machine learning studies, synthesis and biological evaluation of their anti-tuberculosis activity.
https://www.ncbi.nlm.nih.gov/pubmed/30973110
* TODO Machine learning and tubercular drug target recognition.
https://www.ncbi.nlm.nih.gov/pubmed/24245763





* WAIT Ahmed2020 - Non-tuberculous mycobacterial infections—A neglected and emerging problem
** Notes
- Survey paper
- Could be used build up the background for the need for research in NTM
** FileName
- Ahmed2020_NonTuberculosisMycoANeglectedAndEmergingProblem.pdf
** Abstract
- The incidence of NTM infections is rising owing to a growing population of
  immunocompromised and vulnerable individuals, complex medical and surgical
  procedures, as well as increased awareness and diagnostic capabilities.
** FutureWork
- Simpler and more rapid tests would be ideal in making the diagnosis of NTM
  disease more quickly. However, the development of such tests is complicated
  by the large number of NTM species that can cause disease and by the criteria
  for disease, which require more than just the presence of the microorganism.
  As a result, NTM disease will require multiple diagnostic parameters, leading
  to delays and higher costs. More specific biomarkers to monitor the progress
  of treatment and test cure are lacking.
 
* STRT Aze2015 - Genomics and Machine Learning for Taxonomy Consensus: The Mycobacterium tuberculosis Complex Paradigm
** Notes
- Can adopt a similar approach towards the classification of NTB lineages
- Can alter the algorithm to XGBoost to Neural Networks to improve accuracy
** FileName
- Aze2015_GenomicsAndMachine.pdf
** Abstract
- Mycobacterium tuberculosis complex taxonomy has rapidly evolved in the last 20
  years through intensive clinical isolation, advances in sequencing and in the
  description of fast-evolving loci (CRISPR and MIRU-VNTR)

- The objectives of this study were 1) to explicit the consensus that exists
  between the alternative taxonomies, and 2) to provide an on-line tool to ease
  classification of new isolates. Genotyping (24-VNTR, 43-spacers spoli-
  gotypes, IS6110-RFLP) was undertaken for 3,454 clinical isolates from the
  Netherlands (2004-2008). The resulting database was enlarged with African
  isolates to include most human tuberculosis diversity. Assignations were
  obtained using TB-Lineage, MIRU- VNTRPlus, SITVITWEB and an algorithm from
  Borile et al
 
- Original and consensus assignations of the all isolates from the database were
  subsequently implemented into an ensemble learning approach based on Machine
  Learning tool Weka to derive a classification scheme.
 
- When applied to independent datasets, it was able to suggest new sublineages
  such as pseudo-Beijing. This Lineage Prediction tool, efficient on 15-MIRU,
  24-VNTR and spoligotype data is available on the web interface “TBminer.”
 
- We successfully used Machine Learning on a large dataset to set up and make
  available the first consensual taxonomy for human Mycobacterium tuberculosis
  complex
 
** Conclusion
- We developed an approach making use of standard typing data for human M.
tuberculosis isolates to infer a consensual taxonomy concordant with most
up-to-date data on Whole Genome Sequencing diversity.

- We hope that the same approach can benefit other human pathogens having
  alternative taxonomies according to Serotypes, CRISPRtypes, MLST-types such as
  Salmo- nella, Listeria, Brucella, and more broadly to other organisms such as
  bacterial plant- pathogens.
 
* [-] Bagherian2019 - Machine learning approaches and databases for prediction of drug–target interaction: a survey paper
** Notes
- Not directly related to (N)TB
- Survey paper
- Analyzes various ML techniques
- Mentions various drug-target-interaction databases
** FileName
- Bagherian2019_MachineLearning.pdf
** Abstract
- There is a need to develop novel and efficient prediction approaches in order
  to avoid costly and laborious yet not-always-deterministic experiments to
  determine drug–target interactions (DTIs) by experiments alone
- In this article, we describe the data required for the task of DTI prediction
  followed by a comprehensive catalog consisting of machine learning methods and
  databases, which have been proposed and utilized to predict DTIs
- The advantages and disadvantages of each set of methods are also briefly
  discussed
** Conclusion
- Almost all the methods used in DTI prediction, particularly similarity-based
  methods, heavily rely on assertions concerning similar drugs and similar
  targets, the type of database used for the prediction plays a significant
  role.
- Future predictions should rely on more comprehensive inter- nal databases,
  which would require a significant effort to map and curate data across the
  sources that utilize different ways to define, name and identify the drugs and
  targets.

* STRT Cao2016 - Improving Tuberculosis Diagnostics Using Deep Learning and Mobile Health Technologies among Resource-Poor and Marginalized Communities
** Notes
- Image processing algorithms, CNN
- They proposed an online database of X-ray images - by now this might have been developed
** FileName
- Cao2016_ImprovingDiagnosticsUsingDL.pdf
** Abstract
- The combination of machine learning and mobile computing techniques offers a
  unique opportunity to accelerate the TB diagnosis among these communities

- We first introduce major technique barriers and proposed system architecture

- The first activity aims to develop large-scale, real-world and well-annotated
  X-ray image database dedicated for automated TB screening.

- The second research activity focus on developing effective and efficient
  computational models (in particularly, deep convolutional neural networks
  (CNN)-based models) to classify the image into different category of TB
  manifestations
 
- Our future work includes: (1) to further improve the performance of the
  algorithms; and (2) to deploy our system in the city of Carabayllo in Perú, a
  densely occupied urban community and high-burden TB
 
** Conclusion
- The first progress is to build a large-scale, real-world, and well-annotated chest X- ray image
  database dedicated for TB screening.
 
- The second progress is to develop effective and efficient computational model for TB manifestation
  categorization.

- We will continue to develop the large scale, real-world X-ray TB database, as
  well as continuing to improve the performance of the computing algorithms

* STRT Chen2018 - Deep Learning Predicts Tuberculosis Drug Resistance Status from Whole-Genome Sequencing Data
** Notes
- A good in-depth ML based paper
- They've shared high-level implementation details briefly
- Hyperparameters are also in the supplementary material
- I was able to find the code on Github
  https://github.com/biosharp-dotnet/wdnn
- Could apply the same techniques to NTM
- Could change the algorithm and apply on the same data
- The author built upon the previous paper by improving the accuracy of the ML model - we could do the same with NTM
** FileName
- Chen2018_DeepLearningPredictsTuberculosis.pdf
** Abstract
- Using targeted or whole genome sequencing and conventional drug resistance
  phenotyping data from 3,601 Mycobacterium tuberculosis strains, 1,228 of which
  were multidrug resistant, we implemented the first multitask deep learning
  framework to predict phenotypic drug resistance to 10 anti-tubercular drugs
 
- The proposed wide and deep neural network (WDNN) achieved improved predictive
  performance compared to regularized logistic regression and random forest
 
** Conclusion
- We demonstrate that L2 regression and MD-WDNN trained on a larger diverse
  dataset using a method of aggregating rare variants outperforms our previously
  reported random forest model. (Chen, 2018)

- A few prior studies have utilized algorithmic or machine learning methods
  using genomic data to account for the complex relationship between genotype
  and drug resistance in MTB
 
* STRT Chen2019 - Beyond multidrug resistance: Leveraging rare variants with machine and statistical learning models in Mycobacterium tuberculosis resistance prediction
** Notes
- A good in-depth ML based paper
- Could apply the same techniques to NTM
- Could change the algorithm and apply on the same data
** FileName
- Chen2019_BeyondMultiDrugResistance.pdf
** Abstract
- Whole genome sequencing of clinical Mycobacterium tuberculosis isolates
  promises to circumvent the long wait times and limited scope of conventional
  phenotypic antimicrobial susceptibility, but gaps remain for predicting
  phenotype accurately from genotypic data especially for certain drugs.
 
- We collected targeted or whole genome sequencing and conventional drug
  resistance phenotyping data from 3601 Mycobacterium tuberculosis strains
  enriched for resistance to first- and second-line drugs, with 1228 multidrug
  resistant strains

- We investigated the utility of (1) rare variants and variants known to be
  determinants of resistance for at least one drug and (2) machine and
  statistical learning architectures in predicting phenotypic drug resistance to
  10 anti-tuberculosis drugs

** Conclusion
- Our approach allowed us to gain new insights into the relative im- portance of
  specific genetic variants for resistance prediction
 
- In summary, we present an exploration of machine learning and traditional
  statistical models to identify the resistance of MTB isolates to 10
  anti-tuberculosis drugs from whole genome sequencing data.
 
- Our models trained on rare and common genetic variants achieved
  state-of-the-art performance on a large, aggregated TB dataset, with
  prediction times of less than a tenth of a second, demonstrating the efficacy
  of our model as a diagnostic tool for MTB drug resistance.

- The MD-WDNN represented the first multidrug model to our knowledge that
incorporated a high number of genotypic predictors known to be important to
determining resistance for one or more included drugs

 
* [-] Ching2018 - Opportunities and obstacles for deep learning in biology and medicine
** Notes
- Found the code https://github.com/greenelab/deep-review
- Can use this paper to build up the background for using DL in MTB and NTM analysis
** FileName
- Ching2018_OpportunitiesAndObstaclesForDLInBiology.pdf
** Abstract
- Following from an extensive literature review, we find that deep learning has
  yet to revolutionize biomedicine or definitively resolve any of the most
  pressing challenges in the field, but promising advances have been made on the
  prior state of the art
- The limited amount of labelled data for training presents problems in some
  domains, as do legal and privacy constraints on work with sensitive health
  records.

** Conclusion
- The most challenging tasks may be those in which predictions are used directly
  for downstream model- ling or decision-making, especially in the clinic. As an
  example, errors in sequence variant calling will be amplified if they are used
  directly for genome-wide association studies.
 
- In addition, the stochasticity and complexity of biological sys- tems imply
  that for some problems, for instance, predicting gene regulation in disease,
  perfect accuracy will be unattainable
 
* STRT Deelder2019 - Machine Learning Predicts Accurately Mycobacterium tuberculosis Drug Resistance From Whole Genome Sequencing Data
** Notes
- Need to request code from authors
- Good ML oriented paper
** FileName
- Deelder2019_MLPredictsAccurately.pdf
** Abstract
- We applied machine learning approaches to 16,688 M. tuberculosis isolates that
  have undergone WGS and laboratory drug-susceptibility testing (DST) across 14
  antituberculosis drugs, with 22.5% of samples being multidrug resistant and
  2.1% being extensively drug resistant.
 
- We fitted separate models for each drug, with and without “co-occurrent
  resistance” markers known to be causing resistance to drugs other than the one
  of interest. Predictive performance was measured using sensitivity,
  specificity, and the area under the receiver operating characteristic curve,
  assuming DST results as the gold standard.

- Overall, the gradient-boosted-tree models performed better than the
  classification-tree models.

- Our work demonstrates the utility of machine learning as a flexible approach
  to drug resistance prediction that is able to accommodate a much larger number
  of predictors and to summarize their predictive ability, thus assisting
  clinical decision making and single nucleotide polymorphism detection in an
  era of increasing WGS data generation.
 
** Conclusion

- The predictive performance was highest for resistance to first-line drugs,
  and multidrug-resistant tuberculosis (area under the receiver operating characteristic curve above
  96%), and lowest for third- line drugs (area under the curve below 85%).
 
** Supplementary
*** Deelder2019_MLPredictsAccurately_Data_Sheet_1.pdf
* [?] Djout2016 - Predictive modeling targets thymidylate synthase ThyX in Mycobacterium tuberculosis
** Notes
- This requires more knowledge of chemistry and perhaps also relies on lab based experiments
** FileName
- Djout2016_PredictiveModeling.pdf
** Abstract
- ThyX is an essential thymidylate synthase
that is mechanistically and structurally unrelated to the human enzyme. DNA
gyrase is a DNA topoisomerase present in bacteria and plants but not animals.
The current study set out to understand the structure-activity relationships of
these targets in Mtb using a combination of cheminformatics and in vitro
screening.
** Conclusion
* STRT Donohue2018 - Increasing nontuberculous mycobacteria reporting rates and species diversity identified in clinical laboratory reports
** Notes
- This is a survey report about NTM across a couple decades
- Could be used in building up the background context
** FileName
- Donohue2018_IncreasingNTMReportingRates.pdf
** Abstract
- Changes in NTM diversity were observed in complex/groups known to be
  clinically significant. Between 1994 and 2014 the rate implicating M.
  abscesses-chelonae group and M. avium complex increased by 322 and 149%,
  respectively.
** Conclusion
- Knowledge of the NTM species most frequently associ- ated with adverse human
  health consequences will assist epidemiological investigators to identify
  likely sources and modes of exposure associated with these types of in-
  fections.
- As the U.S. population ages, the public health burden from NTM associated
  disorders is expected to increase.
 
* [-] Doshi2017 - Tuberculosis control, and the where and why of artificial intelligence
** Notes
- Survey paper
- Can be used for building background context
** FileName
- Doshi2017_TuberculosisControl.pdf
** Abstract
** Conclusion
* [X] Ekins2013 - Enhancing Hit Identification in Mycobacterium tuberculosis Drug Discovery Using Validated Dual-Event Bayesian Models
** Notes
- Requires too much domain knowledge
- Perhaps uses an older technique i.e. HTS for analysis
- Could use other algorithms on the data used in this study
** FileName
- Ekins2013_EnhancingHitIdentification.pdf
** Abstract
- High-throughput screening (HTS) in whole cells is widely pursued to find
  compounds active against Mycobacterium tuberculosis (Mtb) for further
  development towards new tuberculosis (TB) drugs
- We have recently built and validated Bayesian machine learning models for
  predicting compounds with activity against Mtb based on publicly available
  large-scale HTS data from the Tuberculosis Antimicrobial Acquisition
  Coordinating Facility
** Conclusion
* [X] Ekins2013 - Fusing Dual-Event Data Sets for Mycobacterium tuberculosis Machine Learning Models and Their Evaluation
** Notes
- Requires too much domain knowledge
- Perhaps uses an older technique i.e. HTS for analysis
- Could use other algorithms on the data used in this study
** FileName
- Ekins2013_FusingDualEvent.pdf
** Abstract
- A cheminformatics data-fusion
approach followed by Bayesian machine learning, Support Vector Machine, or Recursive
Partitioning model development (based on publicly available Mtb screening data) was used to
compare individual data sets and subsequent combined models.
- We demonstrate that
combining three data sets incorporating antitubercular and cytotoxicity data in Vero cells
from our previous screens results in external validation receiver operator curve (ROC) of
0.83 (Bayesian or RP Forest)
** Conclusion
* [X] Ekins2014_AreBiggerDataSets.pdf
** Notes
- Requires too much domain knowledge
- Perhaps uses an older technique i.e. HTS for analysis
- Could use other algorithms on the data used in this study
** Title
** Abstract
** Conclusion
* [X] Ekins2014_CombiningComputationalMethods.pdf
** Notes
- Requires too much domain knowledge
- Perhaps uses an older technique i.e. HTS for analysis
- Could use other algorithms on the data used in this study
** Title
** Abstract
** Conclusion
* [X] Ekins2016_MachineLearningModel.pdf
** Notes
- Requires too much domain knowledge
- Perhaps uses an older technique i.e. HTS for analysis
- Could use other algorithms on the data used in this study
** Title
** Abstract
** Conclusion
* [X] Ekins2017_MachineLearning.pdf
** Notes
- Requires too much domain knowledge
- Perhaps uses an older technique i.e. HTS for analysis
- Could use other algorithms on the data used in this study
** Title
** Abstract
** Conclusion
* [-] Engle2019 - Performance of Qure.ai automatic classifiers against a large annotated database of patients with diverse forms of tuberculosis
** Notes
- Image processing
- Mentiones the database source, NIH
- Has CSV as supplementary data
** FileName
- Engle2019_PerformanceOfQureAI.pdf
** Abstract
- Availability of trained radiologists for fast processing of CXRs in regions
  burdened with tuberculosis always has been a challenge, affecting both timely
  diagnosis and patient monitoring.
 
- The Qure.ai qXR arti- ficial intelligence automated CXR interpretation tool,
  was blind-tested on the 346 radiologist- annotated CXRs from the TBPP
  database.

- We conclude that applying fully automated Qure.ai CXR analysis tool is useful
  for fast, accurate, uniform, large-scale CXR annotation assistance, as it
  performed well even for DR-TB cases that were not used for initial training.
 
** Conclusion
- We demonstrated that the Qure.ai qXR CXR annotations for cavity, nodule,
  pleural effusion, and hilar lymphadenopathy, are in statistical agreement with
  radiologist CXR annotations.
 
- A corresponding analysis of patient case matched
  CT image annotations recorded within 30 days of a CXR supports this result,
  demonstrating statistical significance for cavity, pleural effusion, hilar
  lymphadenopathy, and atelectasis.
 
* [-] Greif2020 - Species Distribution and Isolation Frequency of Nontuberculous Mycobacteria, Uruguay
** Notes
- Survey paper
** FileName
- Greif2020_FrequencyOfNTM.pdf
** Abstract
-  Nontuberculous mycobacteria (NTM) increasingly are recognized as
  opportunistic pathogens of humans.
-  NTM species distribution is well documented in Europe and North America
** Conclusion
- Our findings indicate that rate of NTM have risen nearly 5-fold (4.79) in
  Uruguay, from 0.33 cas- es/100,000 inhabitants in 2006 to 1.57 cases/100,000
  inhabitants in 2018.
 
* [-] Hicks2019 - Evaluation of parameters affecting performance and reliability of machine learning-based antibiotic susceptibility testing from whole genome sequencing data
** Notes
- Can perform the mentioned analysis on the MTB and NTM data
- The paper focuses on the factors affecting the application and clinical application of ML models
** FileName
- Hicks2019_EvaluationOfParameters.pdf
** Abstract
- There has been no systematic evaluation of factors that may influence
  performance of ML models, how they might apply to and vary across clinical
  populations, and what the implications might be in the clinical setting
 
- We performed a meta-analysis of seven large Neisseria gonorrhoeae datasets, as
  well as Klebsiella pneumoniae and Acinetobacter baumannii datasets, with whole
  genome sequence data and antibiotic susceptibility phenotypes using set
  covering machine classifi- cation, random forest classification, and random
  forest regression models to predict resis- tance phenotypes from genotype.
 
- We demonstrate how model performance varies by drug, dataset, resistance
  metric, and species, reflecting the complexities of generating clinically
  relevant conclusions from machine learning-derived models.

- Our results highlight significant biological and technical challenges
  facing the application of machine learning-based prediction of antibiotic
  resistance as a diagnostic tool.

** Conclusion
* STRT Hussain2018 - Predicting treatment outcome of drug-susceptible tuberculosis patients using machine-learning models
** Notes
- Can use a different algorithm (XgBoost) on the dataset
- Sample data and complete code is shared
  https://github.com/biosharp-dotnet/tuberculosis-predictive-analytics
- Need to find the full dataset of 4000 surveyed patients
** FileName
- Hussain2018_PredictingTreatmentOutcomes.pdf
** Abstract
- Tuberculosis (TB) is a deadly contagious disease and a serious global health
  problem. It is curable but due to its lengthy treatment process, a patient is
  likely to leave the treatment incomplete, leading to a more lethal, drug
  resistant form of disease.
 
- We aim to facilitate TB programs by predicting the outcome of the treatment of
  a particular patient at the start of treatment so that their health workers
  can be utilized in a targeted and cost-effective way.

- The problem was modeled as a classification problem, and the outcome of
  treatment was predicted using state-of-art implementations of 3 machine learning algorithms
 
** Conclusion
- Empirical results using data of more than 4000 patients reveal that we can
  predict with more than 76% accuracy whether a TB patient would complete his (or her) treatment or not
-
* STRT Jamal2020 - Artificial Intelligence and Machine learning based prediction of resistant and susceptible mutations in Mycobacterium tuberculosis
** Notes
- Used many ML algorithms, 85% accuracy
- Could use XgBoost
- Could conduct a similar study for NTM
- Mentions many online bio databases
** FileName
- Jamal2020_AIAndMLBasedPredictive.pdf
** Abstract
- The present work is a computational framework that uses artificial
  intelligence (AI) based machine learning (ML) approaches for predicting
  resistance in the genes rpoB, inhA, katG, pncA, gyrA and gyrB for the drugs
  rifampicin, isoniazid, pyrazinamide and fluoroquinolones

- The single nucleotide variations were represented by several sequence and
  structural features that indicate the influence of mutations on the target
  protein coded by each gene.
 
** Conclusion

- The present study proposes an AI/ML method to classify resistant and susceptible
  mutations in TB and predict novel resistance conferring mutations.
 
- The impact of the reported mutations was captured in the form of changes in the amino acid
  residues, and the consequent change in properties vis-a-vis wild-type and mutant
  proteins and represented as features used to train the models.

- The classification model was generated for each gene and predictions were made for
  SNVs linked with each gene for each drug

* STRT Kavvas2018 - Machine learning and structural analysis of Mycobacterium tuberculosis pan-genome identifies genetic signatures of antibiotic resistance
** Notes
- They developed and online platform
 
- Can be applied to NTM

- Code is available
  https://github.com/biosharp-dotnet/microbial_AMR_ML
** FileName
- Kavvas2018_MachineLearning_.pdf
** Abstract
- The many publicly available datasets describing its AMR characteristics demand
  disparate data-type analyses.
 
- Here, we develop a reference strain-agnostic computational platform that uses
  machine learning approaches, complemented by both genetic interaction analysis
  and 3D structural mutation-mapping, to identify signatures of AMR evolution to
  13 antibiotics.

- First, a pan-genome analysis shows that M. tuberculosis is highly conserved
  with sequenced variation concentrated in PE/PPE/PGRS genes.

- Second, the platform corroborates 33 genes known to confer resistance and identifies 24
  new genetic signatures of AMR.

- Third, 97 epistatic interactions across 10 resistance classes are revealed.

- Fourth, detailed structural analysis of these
  genes yields mechanistic bases for their selection.

- The platform can be used to study other human pathogens

** Conclusion

- The platform was applied to 1595 sequenced strains to yield results in four
  categories: pan-genome properties, identification of genes conferring
  antibiotic resistance, their epistatic interactions, and protein structure
  based mechanistic insights.
 
* Khanna2018 - Ensemble Technique for Prediction of T-cell Mycobacterium tuberculosis Epitopes
** Notes
-
** FileName
- Khanna2018_EnsembleTechnique.pdf
** Abstract
- Development of an effective machine-learning model for T-cell Mycobacterium
  tuberculosis (M. tuberculosis) epitopes is beneficial for saving biologist’s
  time and effort for identifying epitope in a targeted antigen.

- The proposed method is able to work with variable length epitopes having size
even greater than 9-mers. Identification of T-cell or B-cell epitopes in the
targeted antigen is the main goal in designing epitope-based vaccine,
immune-diagnostic tests and antibody production

** Conclusion
* Killian2019_LearningToPrescribe.pdf
** Title
** Abstract
** Conclusion
* Kouchaki2019_ApplicationOfML.pdf
** Title
** Abstract
** Conclusion
* Kouchaki2020_MultiLabelRandomForest.pdf
** Title
** Abstract
** Conclusion
** Supplementary
*** Kouchaki2020_MultiLabel.zip
*** Kouchaki2020_MultiLabel_DataSheet_1.pdf
*** Kouchaki2020_MultiLabel_DataSheet_2.pdf
*** Code
Kouchaki2020_MultiLabelSLRF/checkmutations.py
Kouchaki2020_MultiLabelSLRF/common_functions.py
Kouchaki2020_MultiLabelSLRF/cvcodes.py
Kouchaki2020_MultiLabelSLRF/demo-mtbmlrf.py
Kouchaki2020_MultiLabelSLRF/ensemble_learning_multilabel.py
Kouchaki2020_MultiLabelSLRF/fakefeat.csv
Kouchaki2020_MultiLabelSLRF/fakepheno.csv
Kouchaki2020_MultiLabelSLRF/feature_extraction.py
Kouchaki2020_MultiLabelSLRF/load-dataset.py
Kouchaki2020_MultiLabelSLRF/mutation_ranking.py
Kouchaki2020_MultiLabelSLRF/print_stats.py
Kouchaki2020_MultiLabelSLRF/readme
Kouchaki2020_MultiLabelSLRF/treeplot.py

* Kovalishyn2019_HybridDesign.pdf
** Title
** Abstract
** Conclusion
* Kumari2019_AGeneticProgramming.pdf
** Title
** Abstract
** Conclusion
* Lai2019_ComparisonOfThePredictiveOutcomes.pdf
** Abstract
** Conclusion
* Lane2018_ComparingAndValidating.pdf
** Abstract
** Conclusion
* Lin2001_ConservedCodonComposition.pdf
** Abstract
** Conclusion
* LokeshKumar2019_PredictionOfMultiDrugResistant.pdf
** Abstract
** Conclusion
* Mahe2019_ALargeScaleEvaluationTBProfiler.pdf
** Abstract
** Conclusion
* Marino2016_ComputationalAndEmpirical.pdf
** Abstract
** Conclusion
* Marques2019_PulmonaryNTMInfections.pdf
** Abstract
** Conclusion
* Meldenez2015_OnCombiningMultiple.pdf
** Abstract
** Conclusion
* Mikusova2016_LearningFromThePast.pdf
** Abstract
** Conclusion
* Ngo2019_GenomicPrediction.pdf
** Abstract
** Conclusion
* Periwal2011_PredictiveModels.pdf
** Abstract
** Conclusion
* Ratnatunga2020_RiseOfNTMLungDisease.pdf
** Abstract
** Conclusion
* Romero2020_DecisionTree.pdf
** Abstract
** Conclusion
** Supplementary
*** Romero2020_DecisionTree_Corrigendum.pdf
* Sauer2018_FeatureSelection.pdf
** Abstract
** Conclusion
* Schiff2018_ClinicalRelevanceOfNTM.pdf
** Abstract
** Conclusion
* Sergeev2016_GenomeWide.pdf
** Abstract
** Conclusion
* Vizcaino2010_ComputatationalPrediction.pdf
** Abstract
** Conclusion
* Waman2019_MycobacterialGenomics.pdf
** Abstract
** Conclusion
* Wang2020_ADeepLearningBasedMethod.pdf
** Abstract
** Conclusion
* Weiner2017_HighThroughput.pdf
** Abstract
** Conclusion
* Wilder2019_ImprovingTuberculosis.pdf
** Abstract
** Conclusion
* Yang2017_MachineLearning.pdf
** Abstract
** Conclusion
* Yang2019_DeepAMRForPredicting.pdf
** Abstract
** Conclusion
* Zhang2020_AnIntegratedMLApproach.pdf
** Abstract
** Conclusion
