#+TITLE: Other Papers
#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup
#+HTML_HEAD: <style> p{margin-bottom:5px;}</style>
#+HTML_HEAD: <style> li{margin-bottom:10px}</style

* TODO Advances in Computational Studies of Potential Drug Targets in Mycobacterium tuberculosis.
https://www.ncbi.nlm.nih.gov/pubmed/30084331
* TODO Hybrid design of isonicotinic acid hydrazide derivatives: machine learning studies, synthesis and biological evaluation of their anti-tuberculosis activity.
https://www.ncbi.nlm.nih.gov/pubmed/30973110
* TODO Machine learning and tubercular drug target recognition.
https://www.ncbi.nlm.nih.gov/pubmed/24245763





* WAIT Ahmed2020 - Non-tuberculous mycobacterial infections—A neglected and emerging problem
** Notes
- Survey paper
- Could be used build up the background for the need for research in NTM
** FileName
- Ahmed2020_NonTuberculosisMycoANeglectedAndEmergingProblem.pdf
** Abstract
- The incidence of NTM infections is rising owing to a growing population of
  immunocompromised and vulnerable individuals, complex medical and surgical
  procedures, as well as increased awareness and diagnostic capabilities.
** FutureWork
- Simpler and more rapid tests would be ideal in making the diagnosis of NTM
  disease more quickly. However, the development of such tests is complicated
  by the large number of NTM species that can cause disease and by the criteria
  for disease, which require more than just the presence of the microorganism.
  As a result, NTM disease will require multiple diagnostic parameters, leading
  to delays and higher costs. More specific biomarkers to monitor the progress
  of treatment and test cure are lacking.
 
* STRT Aze2015 - Genomics and Machine Learning for Taxonomy Consensus: The Mycobacterium tuberculosis Complex Paradigm
** Notes
- Can adopt a similar approach towards the classification of NTB lineages
- Can alter the algorithm to XGBoost to Neural Networks to improve accuracy
** FileName
- Aze2015_GenomicsAndMachine.pdf
** Abstract
- Mycobacterium tuberculosis complex taxonomy has rapidly evolved in the last 20
  years through intensive clinical isolation, advances in sequencing and in the
  description of fast-evolving loci (CRISPR and MIRU-VNTR)

- The objectives of this study were 1) to explicit the consensus that exists
  between the alternative taxonomies, and 2) to provide an on-line tool to ease
  classification of new isolates. Genotyping (24-VNTR, 43-spacers spoli-
  gotypes, IS6110-RFLP) was undertaken for 3,454 clinical isolates from the
  Netherlands (2004-2008). The resulting database was enlarged with African
  isolates to include most human tuberculosis diversity. Assignations were
  obtained using TB-Lineage, MIRU- VNTRPlus, SITVITWEB and an algorithm from
  Borile et al
 
- Original and consensus assignations of the all isolates from the database were
  subsequently implemented into an ensemble learning approach based on Machine
  Learning tool Weka to derive a classification scheme.
 
- When applied to independent datasets, it was able to suggest new sublineages
  such as pseudo-Beijing. This Lineage Prediction tool, efficient on 15-MIRU,
  24-VNTR and spoligotype data is available on the web interface “TBminer.”
 
- We successfully used Machine Learning on a large dataset to set up and make
  available the first consensual taxonomy for human Mycobacterium tuberculosis
  complex
 
** Conclusion
- We developed an approach making use of standard typing data for human M.
tuberculosis isolates to infer a consensual taxonomy concordant with most
up-to-date data on Whole Genome Sequencing diversity.

- We hope that the same approach can benefit other human pathogens having
  alternative taxonomies according to Serotypes, CRISPRtypes, MLST-types such as
  Salmo- nella, Listeria, Brucella, and more broadly to other organisms such as
  bacterial plant- pathogens.
 
* [-] Bagherian2019 - Machine learning approaches and databases for prediction of drug–target interaction: a survey paper
** Notes
- Not directly related to (N)TB
- Survey paper
- Analyzes various ML techniques
- Mentions various drug-target-interaction databases
** FileName
- Bagherian2019_MachineLearning.pdf
** Abstract
- There is a need to develop novel and efficient prediction approaches in order
  to avoid costly and laborious yet not-always-deterministic experiments to
  determine drug–target interactions (DTIs) by experiments alone
- In this article, we describe the data required for the task of DTI prediction
  followed by a comprehensive catalog consisting of machine learning methods and
  databases, which have been proposed and utilized to predict DTIs
- The advantages and disadvantages of each set of methods are also briefly
  discussed
** Conclusion
- Almost all the methods used in DTI prediction, particularly similarity-based
  methods, heavily rely on assertions concerning similar drugs and similar
  targets, the type of database used for the prediction plays a significant
  role.
- Future predictions should rely on more comprehensive inter- nal databases,
  which would require a significant effort to map and curate data across the
  sources that utilize different ways to define, name and identify the drugs and
  targets.

* STRT Cao2016 - Improving Tuberculosis Diagnostics Using Deep Learning and Mobile Health Technologies among Resource-Poor and Marginalized Communities
** Notes
- Image processing algorithms, CNN
- They proposed an online database of X-ray images - by now this might have been developed
** FileName
- Cao2016_ImprovingDiagnosticsUsingDL.pdf
** Abstract
- The combination of machine learning and mobile computing techniques offers a
  unique opportunity to accelerate the TB diagnosis among these communities

- We first introduce major technique barriers and proposed system architecture

- The first activity aims to develop large-scale, real-world and well-annotated
  X-ray image database dedicated for automated TB screening.

- The second research activity focus on developing effective and efficient
  computational models (in particularly, deep convolutional neural networks
  (CNN)-based models) to classify the image into different category of TB
  manifestations
 
- Our future work includes: (1) to further improve the performance of the
  algorithms; and (2) to deploy our system in the city of Carabayllo in Perú, a
  densely occupied urban community and high-burden TB
 
** Conclusion
- The first progress is to build a large-scale, real-world, and well-annotated chest X- ray image
  database dedicated for TB screening.
 
- The second progress is to develop effective and efficient computational model for TB manifestation
  categorization.

- We will continue to develop the large scale, real-world X-ray TB database, as
  well as continuing to improve the performance of the computing algorithms

* STRT Chen2018 - Deep Learning Predicts Tuberculosis Drug Resistance Status from Whole-Genome Sequencing Data
** Notes
- A good in-depth ML based paper
- They've shared high-level implementation details briefly
- Hyperparameters are also in the supplementary material
- I was able to find the code on Github
  https://github.com/biosharp-dotnet/wdnn
- Could apply the same techniques to NTM
- Could change the algorithm and apply on the same data
- The author built upon the previous paper by improving the accuracy of the ML model - we could do the same with NTM
** FileName
- Chen2018_DeepLearningPredictsTuberculosis.pdf
** Abstract
- Using targeted or whole genome sequencing and conventional drug resistance
  phenotyping data from 3,601 Mycobacterium tuberculosis strains, 1,228 of which
  were multidrug resistant, we implemented the first multitask deep learning
  framework to predict phenotypic drug resistance to 10 anti-tubercular drugs
 
- The proposed wide and deep neural network (WDNN) achieved improved predictive
  performance compared to regularized logistic regression and random forest
 
** Conclusion
- We demonstrate that L2 regression and MD-WDNN trained on a larger diverse
  dataset using a method of aggregating rare variants outperforms our previously
  reported random forest model. (Chen, 2018)

- A few prior studies have utilized algorithmic or machine learning methods
  using genomic data to account for the complex relationship between genotype
  and drug resistance in MTB
 
* STRT Chen2019 - Beyond multidrug resistance: Leveraging rare variants with machine and statistical learning models in Mycobacterium tuberculosis resistance prediction
** Notes
- A good in-depth ML based paper
- Could apply the same techniques to NTM
- Could change the algorithm and apply on the same data
** FileName
- Chen2019_BeyondMultiDrugResistance.pdf
** Abstract
- Whole genome sequencing of clinical Mycobacterium tuberculosis isolates
  promises to circumvent the long wait times and limited scope of conventional
  phenotypic antimicrobial susceptibility, but gaps remain for predicting
  phenotype accurately from genotypic data especially for certain drugs.
 
- We collected targeted or whole genome sequencing and conventional drug
  resistance phenotyping data from 3601 Mycobacterium tuberculosis strains
  enriched for resistance to first- and second-line drugs, with 1228 multidrug
  resistant strains

- We investigated the utility of (1) rare variants and variants known to be
  determinants of resistance for at least one drug and (2) machine and
  statistical learning architectures in predicting phenotypic drug resistance to
  10 anti-tuberculosis drugs

** Conclusion
- Our approach allowed us to gain new insights into the relative im- portance of
  specific genetic variants for resistance prediction
 
- In summary, we present an exploration of machine learning and traditional
  statistical models to identify the resistance of MTB isolates to 10
  anti-tuberculosis drugs from whole genome sequencing data.
 
- Our models trained on rare and common genetic variants achieved
  state-of-the-art performance on a large, aggregated TB dataset, with
  prediction times of less than a tenth of a second, demonstrating the efficacy
  of our model as a diagnostic tool for MTB drug resistance.

- The MD-WDNN represented the first multidrug model to our knowledge that
incorporated a high number of genotypic predictors known to be important to
determining resistance for one or more included drugs

 
* [-] Ching2018 - Opportunities and obstacles for deep learning in biology and medicine
** Notes
- Found the code https://github.com/greenelab/deep-review
- Can use this paper to build up the background for using DL in MTB and NTM analysis
** FileName
- Ching2018_OpportunitiesAndObstaclesForDLInBiology.pdf
** Abstract
- Following from an extensive literature review, we find that deep learning has
  yet to revolutionize biomedicine or definitively resolve any of the most
  pressing challenges in the field, but promising advances have been made on the
  prior state of the art
- The limited amount of labelled data for training presents problems in some
  domains, as do legal and privacy constraints on work with sensitive health
  records.

** Conclusion
- The most challenging tasks may be those in which predictions are used directly
  for downstream model- ling or decision-making, especially in the clinic. As an
  example, errors in sequence variant calling will be amplified if they are used
  directly for genome-wide association studies.
 
- In addition, the stochasticity and complexity of biological sys- tems imply
  that for some problems, for instance, predicting gene regulation in disease,
  perfect accuracy will be unattainable
 
* STRT Deelder2019 - Machine Learning Predicts Accurately Mycobacterium tuberculosis Drug Resistance From Whole Genome Sequencing Data
** Notes
- Need to request code from authors
- Good ML oriented paper
** FileName
- Deelder2019_MLPredictsAccurately.pdf
** Abstract
- We applied machine learning approaches to 16,688 M. tuberculosis isolates that
  have undergone WGS and laboratory drug-susceptibility testing (DST) across 14
  antituberculosis drugs, with 22.5% of samples being multidrug resistant and
  2.1% being extensively drug resistant.
 
- We fitted separate models for each drug, with and without “co-occurrent
  resistance” markers known to be causing resistance to drugs other than the one
  of interest. Predictive performance was measured using sensitivity,
  specificity, and the area under the receiver operating characteristic curve,
  assuming DST results as the gold standard.

- Overall, the gradient-boosted-tree models performed better than the
  classification-tree models.

- Our work demonstrates the utility of machine learning as a flexible approach
  to drug resistance prediction that is able to accommodate a much larger number
  of predictors and to summarize their predictive ability, thus assisting
  clinical decision making and single nucleotide polymorphism detection in an
  era of increasing WGS data generation.
 
** Conclusion

- The predictive performance was highest for resistance to first-line drugs,
  and multidrug-resistant tuberculosis (area under the receiver operating characteristic curve above
  96%), and lowest for third- line drugs (area under the curve below 85%).
 
** Supplementary
*** Deelder2019_MLPredictsAccurately_Data_Sheet_1.pdf
* [?] Djout2016 - Predictive modeling targets thymidylate synthase ThyX in Mycobacterium tuberculosis
** Notes
- This requires more knowledge of chemistry and perhaps also relies on lab based experiments
** FileName
- Djout2016_PredictiveModeling.pdf
** Abstract
- ThyX is an essential thymidylate synthase
that is mechanistically and structurally unrelated to the human enzyme. DNA
gyrase is a DNA topoisomerase present in bacteria and plants but not animals.
The current study set out to understand the structure-activity relationships of
these targets in Mtb using a combination of cheminformatics and in vitro
screening.
** Conclusion
* STRT Donohue2018 - Increasing nontuberculous mycobacteria reporting rates and species diversity identified in clinical laboratory reports
** Notes
- This is a survey report about NTM across a couple decades
- Could be used in building up the background context
** FileName
- Donohue2018_IncreasingNTMReportingRates.pdf
** Abstract
- Changes in NTM diversity were observed in complex/groups known to be
  clinically significant. Between 1994 and 2014 the rate implicating M.
  abscesses-chelonae group and M. avium complex increased by 322 and 149%,
  respectively.
** Conclusion
- Knowledge of the NTM species most frequently associ- ated with adverse human
  health consequences will assist epidemiological investigators to identify
  likely sources and modes of exposure associated with these types of in-
  fections.
- As the U.S. population ages, the public health burden from NTM associated
  disorders is expected to increase.
 
* [-] Doshi2017 - Tuberculosis control, and the where and why of artificial intelligence
** Notes
- Survey paper
- Can be used for building background context
** FileName
- Doshi2017_TuberculosisControl.pdf
** Abstract
** Conclusion
* [X] Ekins2013 - Enhancing Hit Identification in Mycobacterium tuberculosis Drug Discovery Using Validated Dual-Event Bayesian Models
** Notes
- Requires too much domain knowledge
- Perhaps uses an older technique i.e. HTS for analysis
- Could use other algorithms on the data used in this study
** FileName
- Ekins2013_EnhancingHitIdentification.pdf
** Abstract
- High-throughput screening (HTS) in whole cells is widely pursued to find
  compounds active against Mycobacterium tuberculosis (Mtb) for further
  development towards new tuberculosis (TB) drugs
- We have recently built and validated Bayesian machine learning models for
  predicting compounds with activity against Mtb based on publicly available
  large-scale HTS data from the Tuberculosis Antimicrobial Acquisition
  Coordinating Facility
** Conclusion
* [X] Ekins2013 - Fusing Dual-Event Data Sets for Mycobacterium tuberculosis Machine Learning Models and Their Evaluation
** Notes
- Requires too much domain knowledge
- Perhaps uses an older technique i.e. HTS for analysis
- Could use other algorithms on the data used in this study
** FileName
- Ekins2013_FusingDualEvent.pdf
** Abstract
- A cheminformatics data-fusion
approach followed by Bayesian machine learning, Support Vector Machine, or Recursive
Partitioning model development (based on publicly available Mtb screening data) was used to
compare individual data sets and subsequent combined models.
- We demonstrate that
combining three data sets incorporating antitubercular and cytotoxicity data in Vero cells
from our previous screens results in external validation receiver operator curve (ROC) of
0.83 (Bayesian or RP Forest)
** Conclusion
* [X] Ekins2014_AreBiggerDataSets.pdf
** Notes
- Requires too much domain knowledge
- Perhaps uses an older technique i.e. HTS for analysis
- Could use other algorithms on the data used in this study
** Title
** Abstract
** Conclusion
* [X] Ekins2014_CombiningComputationalMethods.pdf
** Notes
- Requires too much domain knowledge
- Perhaps uses an older technique i.e. HTS for analysis
- Could use other algorithms on the data used in this study
** Title
** Abstract
** Conclusion
* [X] Ekins2016_MachineLearningModel.pdf
** Notes
- Requires too much domain knowledge
- Perhaps uses an older technique i.e. HTS for analysis
- Could use other algorithms on the data used in this study
** Title
** Abstract
** Conclusion
* [X] Ekins2017_MachineLearning.pdf
** Notes
- Requires too much domain knowledge
- Perhaps uses an older technique i.e. HTS for analysis
- Could use other algorithms on the data used in this study
** Title
** Abstract
** Conclusion
* [-] Engle2019 - Performance of Qure.ai automatic classifiers against a large annotated database of patients with diverse forms of tuberculosis
** Notes
- Image processing
- Mentiones the database source, NIH
- Has CSV as supplementary data
** FileName
- Engle2019_PerformanceOfQureAI.pdf
** Abstract
- Availability of trained radiologists for fast processing of CXRs in regions
  burdened with tuberculosis always has been a challenge, affecting both timely
  diagnosis and patient monitoring.
 
- The Qure.ai qXR arti- ficial intelligence automated CXR interpretation tool,
  was blind-tested on the 346 radiologist- annotated CXRs from the TBPP
  database.

- We conclude that applying fully automated Qure.ai CXR analysis tool is useful
  for fast, accurate, uniform, large-scale CXR annotation assistance, as it
  performed well even for DR-TB cases that were not used for initial training.
 
** Conclusion
- We demonstrated that the Qure.ai qXR CXR annotations for cavity, nodule,
  pleural effusion, and hilar lymphadenopathy, are in statistical agreement with
  radiologist CXR annotations.
 
- A corresponding analysis of patient case matched
  CT image annotations recorded within 30 days of a CXR supports this result,
  demonstrating statistical significance for cavity, pleural effusion, hilar
  lymphadenopathy, and atelectasis.
 
* [-] Greif2020 - Species Distribution and Isolation Frequency of Nontuberculous Mycobacteria, Uruguay
** Notes
- Survey paper
** FileName
- Greif2020_FrequencyOfNTM.pdf
** Abstract
-  Nontuberculous mycobacteria (NTM) increasingly are recognized as
  opportunistic pathogens of humans.
-  NTM species distribution is well documented in Europe and North America
** Conclusion
- Our findings indicate that rate of NTM have risen nearly 5-fold (4.79) in
  Uruguay, from 0.33 cas- es/100,000 inhabitants in 2006 to 1.57 cases/100,000
  inhabitants in 2018.
 
* [-] Hicks2019 - Evaluation of parameters affecting performance and reliability of machine learning-based antibiotic susceptibility testing from whole genome sequencing data
** Notes
- Can perform the mentioned analysis on the MTB and NTM data
- The paper focuses on the factors affecting the application and clinical application of ML models
** FileName
- Hicks2019_EvaluationOfParameters.pdf
** Abstract
- There has been no systematic evaluation of factors that may influence
  performance of ML models, how they might apply to and vary across clinical
  populations, and what the implications might be in the clinical setting
 
- We performed a meta-analysis of seven large Neisseria gonorrhoeae datasets, as
  well as Klebsiella pneumoniae and Acinetobacter baumannii datasets, with whole
  genome sequence data and antibiotic susceptibility phenotypes using set
  covering machine classifi- cation, random forest classification, and random
  forest regression models to predict resis- tance phenotypes from genotype.
 
- We demonstrate how model performance varies by drug, dataset, resistance
  metric, and species, reflecting the complexities of generating clinically
  relevant conclusions from machine learning-derived models.

- Our results highlight significant biological and technical challenges
  facing the application of machine learning-based prediction of antibiotic
  resistance as a diagnostic tool.

** Conclusion
* STRT Hussain2018 - Predicting treatment outcome of drug-susceptible tuberculosis patients using machine-learning models
** Notes
- Can use a different algorithm (XgBoost) on the dataset
- Sample data and complete code is shared
  https://github.com/biosharp-dotnet/tuberculosis-predictive-analytics
- Need to find the full dataset of 4000 surveyed patients
** FileName
- Hussain2018_PredictingTreatmentOutcomes.pdf
** Abstract
- Tuberculosis (TB) is a deadly contagious disease and a serious global health
  problem. It is curable but due to its lengthy treatment process, a patient is
  likely to leave the treatment incomplete, leading to a more lethal, drug
  resistant form of disease.
 
- We aim to facilitate TB programs by predicting the outcome of the treatment of
  a particular patient at the start of treatment so that their health workers
  can be utilized in a targeted and cost-effective way.

- The problem was modeled as a classification problem, and the outcome of
  treatment was predicted using state-of-art implementations of 3 machine learning algorithms
 
** Conclusion
- Empirical results using data of more than 4000 patients reveal that we can
  predict with more than 76% accuracy whether a TB patient would complete his (or her) treatment or not
-
* STRT Jamal2020 - Artificial Intelligence and Machine learning based prediction of resistant and susceptible mutations in Mycobacterium tuberculosis
** Notes
- Used many ML algorithms, 85% accuracy
- Could use XgBoost
- Could conduct a similar study for NTM
- Mentions many online bio databases
** FileName
- Jamal2020_AIAndMLBasedPredictive.pdf
** Abstract
- The present work is a computational framework that uses artificial
  intelligence (AI) based machine learning (ML) approaches for predicting
  resistance in the genes rpoB, inhA, katG, pncA, gyrA and gyrB for the drugs
  rifampicin, isoniazid, pyrazinamide and fluoroquinolones

- The single nucleotide variations were represented by several sequence and
  structural features that indicate the influence of mutations on the target
  protein coded by each gene.
 
** Conclusion

- The present study proposes an AI/ML method to classify resistant and susceptible
  mutations in TB and predict novel resistance conferring mutations.
 
- The impact of the reported mutations was captured in the form of changes in the amino acid
  residues, and the consequent change in properties vis-a-vis wild-type and mutant
  proteins and represented as features used to train the models.

- The classification model was generated for each gene and predictions were made for
  SNVs linked with each gene for each drug

* STRT Kavvas2018 - Machine learning and structural analysis of Mycobacterium tuberculosis pan-genome identifies genetic signatures of antibiotic resistance
** Notes
- They developed and online platform
 
- Can be applied to NTM

- Code is available
  https://github.com/biosharp-dotnet/microbial_AMR_ML
** FileName
- Kavvas2018_MachineLearning_.pdf
** Abstract
- The many publicly available datasets describing its AMR characteristics demand
  disparate data-type analyses.
 
- Here, we develop a reference strain-agnostic computational platform that uses
  machine learning approaches, complemented by both genetic interaction analysis
  and 3D structural mutation-mapping, to identify signatures of AMR evolution to
  13 antibiotics.

- First, a pan-genome analysis shows that M. tuberculosis is highly conserved
  with sequenced variation concentrated in PE/PPE/PGRS genes.

- Second, the platform corroborates 33 genes known to confer resistance and identifies 24
  new genetic signatures of AMR.

- Third, 97 epistatic interactions across 10 resistance classes are revealed.

- Fourth, detailed structural analysis of these
  genes yields mechanistic bases for their selection.

- The platform can be used to study other human pathogens

** Conclusion

- The platform was applied to 1595 sequenced strains to yield results in four
  categories: pan-genome properties, identification of genes conferring
  antibiotic resistance, their epistatic interactions, and protein structure
  based mechanistic insights.
 
* [-] Khanna2018 - Ensemble Technique for Prediction of T-cell Mycobacterium tuberculosis Epitopes
** Notes
- Uses multiple bio and ML packages in R
- Doesn't use XgBoost or H20
- Code hasn't been shared
** FileName
- Khanna2018_EnsembleTechnique.pdf
** Abstract
- Development of an effective machine-learning model for T-cell Mycobacterium
  tuberculosis (M. tuberculosis) epitopes is beneficial for saving biologist’s
  time and effort for identifying epitope in a targeted antigen.
 
- The proposed method is able to work with variable length epitopes having size
  even greater than 9-mers. Identification of T-cell or B-cell epitopes in the
  targeted antigen is the main goal in designing epitope-based vaccine,
  immune-diagnostic tests and antibody production

- The proposed ensemble model achieves 82.0% accuracy, 0.89 specificity, 0.77
  sensitivity with repeated k-fold cross-validation having average accuracy of
  80.61%.
 
** Conclusion
- Three models (decision tree, avNNet and RRF) have been used to design the
  ensemble model which produces high accuracy, Gini, AUC, specificity and
  sensitivity.

- To validate and compare the proposed ensemble model, NetMHC 4.0, NetMHC 2.3
  and CTLpred servers have been considered.
 

* [-] Killian2019 - Learning to Prescribe Interventions for Tuberculosis Patients Using Digital Adherence Data
** Notes
- Wasn't able to find the data or the code in the paper
** FileName
- Killian2019_LearningToPrescribe.pdf
** Abstract
- We analyze data from one city served by 99DOTS, a phone-call- based DAT
  deployed for Tuberculosis (TB) treatment in India where nearly 3 million
  people are afflicted with the disease each year

- We then construct a deep learning model, demonstrate its interpretability, and
  show how it can be adapted and trained in three different clinical scenarios
  to better target and improve patient care.
 
** Conclusion
- We finally show that tailoring our model for a specific intervention via
  decision-focused learning can improve performance by a further 15%.
* WAIT Kouchaki2019 - Application of machine learning techniques to tuberculosis drug resistance analysis
** Notes
- I've asked the author to provide the source code via ResearchGate
- They've used 6 ML classifiers, not XgBoost or NeuralNetworks
** FileName
- Kouchaki2019_ApplicationOfML.pdf
** Abstract
- Machine learning methods have been widely applied for timely predicting
  resistance of MTB given a specific drug and identifying resistance markers.
  However, they have been not validated on a large cohort of MTB samples from
  multi-centers across the world in terms of resistance prediction and
  resistance marker identification

- Several machine learning classifiers and linear dimension re- duction
  techniques were developed and compared for a cohort of 13 402 isolates
  collected from 16 countries across 6 continents and tested 11 drugs.
 
** Conclusion
- Developing machine learning techniques is especially important to im- prove TB
  resistance prediction, mainly sensitivity for less-studied drugs.
-
** Supplementary
*** Kouchaki2019_ApplicationOfML_Supplementary.pdf
* STRT Kouchaki2020 - Multi-Label Random Forest Model for Tuberculosis Drug Resistance Classification and Mutation Ranking
** Notes
- Source code and data are both available
** FileName
- Kouchaki2020_MultiLabelRandomForest.pdf
** Abstract
- Due to standard regimens for the use of first-line antibiotics, resistance
  co-occurrence, in which samples are resistant to multiple drugs, is common.
  Analysing all drugs simultaneously should therefore enable patterns reflecting
  resistance co-occurrence to be exploited for resistance prediction

- Here, multi-label random forest (MLRF) models are compared with single-label
  random forest (SLRF) for both predicting phenotypic resistance from whole
  genome sequences and identifying important mutations for better prediction of
  four first-line drugs in a dataset of 13402 Mycobacterium tuberculosis
  isolates.
  
** Conclusion
** Supplementary
*** Kouchaki2020_MultiLabel.zip
*** Kouchaki2020_MultiLabel_DataSheet_1.pdf
*** Kouchaki2020_MultiLabel_DataSheet_2.pdf
* [-] Kovalishyn2019 - Hybrid Design of Isonicotinic Acid Hydrazide Derivatives: Machine Learning Studies, Synthesis and Biological Evaluation of their Anti- tuberculosis Activity
** Notes
- Is inclined more towards Chemistry (reagents) wrt TB
** FileName
- Kovalishyn2019_HybridDesign.pdf
** Abstract
- The goal of this work is to identify potent small molecule anti-TB agents by
  machine learning, synthesis and biological evaluation.

- The On-line Chemical Database and Modeling Environment (OCHEM) was used to
  build pre- dictive machine learning models. Seven compounds were synthesized
  and tested in vitro for their an- titubercular activity against H37Rv and
  resistant Mtb strains.

-
** Conclusion
- The goal of this work was to investigate isoniazid- thiazole hybrid compounds
  taking into consideration the key structural futures known to be important for
  their antituber- cular activity.

- The created binary classification models demonstrated good balanced accuracy.
  The predictive power of the binary classifiers was tested by a 5-fold cross-
  validation and resulted in balanced accuracies of 61–78 %. Seven new compounds
  were synthesized and their activity against Mtb H37Rv and MDR strains was
  evaluated at two concentrations (1.5 and 50 μМ) using rifampin and isoniazid
  as controls.
 
* [-] Kumari2019 - A genetic programming-based approach to identify potential inhibitors of serine protease of Mycobacterium tuberculosis
** Notes
- Uses Genetic algorithms and ML algorithms as well
- Data or code isn't available
** FileName
- Kumari2019_AGeneticProgramming.pdf
** Abstract
- We applied genetic programming approaches to understand the impact of
  descriptors on inhibitory effects of serine protease inhibitors of
  Mycobacterium tuberculosis (Mtb) and the discovery of new in- hibitors as drug
  candidates

- The experimental dataset of serine protease inhibitors of Mtb descriptors was
  optimized by genetic algorithm (GA) along with the correlation-based feature
  selection (CFS) in order to develop predictive models using machine-learning
  algorithms.

- The use of CFS-GA with random forest-enhanced classification accuracy and
  predicted new serine protease inhibitors of Mtb, which can be used for better
  drug development against tuberculosis.
 
** Conclusion
-  Comparative analysis of statistical measures for four different
  machine-learning algorithms revealed that RF models with CFS-GA performed
  better than the others.

- The best RF models with CFS-GA predicted new serine protease inhibitors of
  Mtb, which can be used for better drug development against tuberculosis
 
* [-] Lai2019 - Comparison of the Predictive Outcomes for Anti-Tuberculosis Drug-Induced Hepatotoxicity by Different Machine Learning Techniques
** Notes
- Good ML oriented paper
- Can't find the data or code
** FileName
- Lai2019_ComparisonOfThePredictiveOutcomes.pdf
** Abstract
- The study compared the performance of artificial neural network, support
  vector machine and random forest on predicting anti-tuberculosis drugs induced
  hepatotoxicity.

- Combining genomic and clinical data can further increase the area under
  receiver operating characteristic curve than using genomic or clinical data
  alone.

- Nine models were created with 7 clinical factors and 4 genotypes
 
** Conclusion
* [-] Lane2018 - Comparing and Validating Machine Learning Models for Mycobacterium tuberculosis Drug Discovery
** Notes
- Involves chemistry
** FileName
- Lane2018_ComparingAndValidating.pdf
** Abstract
- The need to develop new treatments for those infected with Mycobacterium
  tuberculosis (Mtb) has led to many large-scale phenotypic screens and many
  thousands of new active compounds identified in vitro

- We have curated small molecule Mtb data and developed new models with a total
  of 18,886 molecules with activity cutoffs of 10 μM, 1 μM, and 100 nM. These
  data sets were used to evaluate different machine learning methods (including
  deep learning) and metrics and to generate predictions for additional
  molecules published in 2017

- We have also compared these models with additional machine learning algorithms
  showing Bayesian machine learning models con- structed with literature Mtb
  data generated by different laboratories generally were equivalent to or
  outperformed deep neural networks with external test sets.
 
** Conclusion
* [X] Lin2001 - Conserved codon composition of ribosomal protein coding genes in Escherichia coli, Mycobacterium tuberculosis and Saccharomyces cerevisiae: lessons from supervised machine learning in functional genomics
** Notes
- Deals with codons and homologs etc. No idea.
** FileName
- Lin2001_ConservedCodonComposition.pdf
** Abstract
** Conclusion
* [?] LokeshKumar2019 - Prediction of Multi Drug Resistant Tuberculosis using Machine Learning Techniques
** Notes
- Survey paper
- Offers quick overview of various algorithms with accuracy and other characteristics
** FileName
- LokeshKumar2019_PredictionOfMultiDrugResistant.pdf
** Abstract
- We review different Machine Learning Approaches to predict MDR-TB. Different
  feature estimation methods, execution of distinct machine learning models also
  have been explored.
- AdaBoost ensemble algorithm gave the highest accuracy of all
** Conclusion
* [X] Mahe2019 - A large scale evaluation of TBProfiler and Mykrobe for antibiotic resistance prediction in Mycobacterium tuberculosis
** Notes
- Doesn't directly relate to the dissertation
** FileName
- Mahe2019_ALargeScaleEvaluationTBProfiler.pdf
** Abstract
** Conclusion
* [-] Marino2016 - Computational and Empirical Studies Predict Mycobacterium tuberculosis-Specific T Cells as a Biomarker for Infection Outcome
** Notes
- They conducted their own experiments

** FileName
- Marino2016_ComputationalAndEmpirical.pdf
** Abstract
- Identifying biomarkers for tuberculosis (TB) is an ongoing challenge in
  developing immuno- logical correlates of infection outcome and protection.

- To effectively predict biomarkers for infection progression in any disease,
  including TB, large amounts of experi- mental data are required to reach
  statistical power and make accurate predictions.

- Machine learning techniques were used to interrogate the experimental NHP
  datasets without identifying any potential TB biomarker. In parallel, we used
  our extensive novel NHP datasets to build and calibrate a multi-organ
  computational model that combines what is occurring at the site of infection
  (e.g., lung) at a single granuloma scale with blood level readouts that can be
  tracked in mon- keys and humans.
 
** Conclusion
* [-] Marques2019 - Pulmonary nontuberculous mycobacterial infections: presumptive diagnosis based on the international microbiological criteria adopted in the state of São Paulo, Brazil, 2011-2014
** Notes
- Survey paper for NTM
- Can be used for building up the background
** FileName
- Marques2019_PulmonaryNTMInfections.pdf
** Abstract
- The objective of the present study was to determine the frequency at which the
  various NTM species are identified among selected individuals and in potential
  cases of pulmonary nontuberculous mycobacterial infection.
** Conclusion
- Although various NTM species were identified among the individuals studied,
  those presumptively identified most frequently on the basis of the
  microbiological criteria adopted in the state of São Paulo were the ones that
  are most commonly associated with pulmonary nontuberculous mycobacterial
  infection worldwide or in specific geographic regions.
 
* [-] Meldenez2015 - On Combining Multiple-Instance Learning and Active Learning for Computer-Aided Detection of Tuberculosis
** Notes
- Image processing, radiography
** FileName
- Meldenez2015_OnCombiningMultiple.pdf
** Abstract
- The major advantage of multiple-instance learning (MIL) applied to a
  computer-aided detection (CAD) system is that it allows optimizing the latter
  with case-level labels instead of accurate lesion outlines as traditionally
  required for a supervised approach.

- As shown in previous work, a MIL-based CAD system can perform comparably to
  its supervised counterpart considering complex tasks such as chest radiograph
  scoring in tuberculosis (TB) detection. However, despite this remarkable
  achievement, the uncertainty inherent to MIL can lead to a less satisfactory
  outcome if analysis at lower levels (e.g., regions or pixels) is needed.

- To minimize the labeling effort, we develop a novel instance selection
  mechanism that exploits the MIL problem definition through one-class
  classification.
 
** Conclusion
* [-] Mikusova2016 - Learning from the past for TB drug discovery in the future
** Notes
- Involves chemistry
- Survey paper
- Can be used to build up the context for Drug-Target-Interaction
** FileName
- Mikusova2016_LearningFromThePast.pdf
** Abstract
- Tuberculosis drug discovery has shifted in recent years from a primarily
  target-based approach to one that uses phenotypic high-throughput screens.

- It is clear that we still have much to learn about the drug targets and the
  complex effects of the drugs on Mycobacterium tuberculosis.

- We propose a more integrated approach that learns from earlier drug discovery
  efforts that could help to move drug discovery forward.
 
** Conclusion
* [-] Ngo2019 - Genomic prediction of tuberculosis drug- resistance: benchmarking existing databases and prediction algorithms
** Notes
- This paper seems important but I'm unable to see how to use this in the dissertation.
** FileName
- Ngo2019_GenomicPrediction.pdf
** Abstract
- It is possible to predict whether a tuberculosis (TB) patient will fail to
  respond to specific antibiotics by sequencing the genome of the infecting
  Mycobacterium tuberculosis (Mtb) and observing whether the pathogen carries
  specific mutations at drug-resistance sites.

- Here, we evaluate the performance of four popular tools (TBProfiler, MyKrobe,
  KvarQ, PhyResSE) with 6746 isolates compiled from publicly available
  databases, and subsequently identify highly probable phenotyping errors in the
  databases by genetically predicting the drug phenotypes using all four
  software.

- Our results show that these bioinformatics tools generally perform well in
  predicting the resistance status for two key first-line agents (isoniazid,
  rifampicin), but the accuracy is lower for second-line injectables and
  fluoroquinolones.
 
** Conclusion

- The use of whole-genome sequencing to replace conventional laboratory-based
  drug-susceptibility testing reduces the time taken to culture and test against
  individual drugs, but requires sophisticated bioinformatics algorithms to be
  designed and validated to translate the genetic information into drug
  susceptibility phenotypes.

- Using latent class modeling, we have identi- fied which isolates in the
  existing databases are likely to present erroneous DST phenotypes and
  recalibrated the performance of these bioinformatics software adjusting for
  errors in the existing databases.
 
- However, we still observe low sensitivity in detecting resistance to ETO,
  PAS, PTO, and PZA.

- Without a clear understanding to the genetic biomarkers of drug resistance or
  to their pene- trance, or at least more powerful algorithms that can pick up
  additional intricacies of resistance across multiple drugs, such as what have
  been done for HIV and cancer [22–24], the ability to successfully predict the
  presence of drug-resistance is reduced.
 
* [-] Periwal2011 - Predictive models for anti-tubercular molecules using machine learning on high-throughput biological screening datasets
** Notes
- Could build upon this paper by using XgBoost and other classification
  algorithms
- They've used Weka
- Data is available
- Code is not available
- They've also relied on some closed-source software
** FileName
- Periwal2011_PredictiveModels.pdf
** Abstract
- Recent reports suggest that Mtb has been developing resistance to the widely
  used anti-tubercular drugs resulting in the emergence and spread of multi
  drug-resistant (MDR) and extensively drug-resistant (XDR) strains throughout
  the world.

- Whole organism screens on the other hand are target-agnostic and have been now
  widely employed as an alternative for lead identification but they are limited
  by the time and cost involved in running the screens for large compound
  libraries.
 
** Conclusion

- We have employed a systematic and comprehensive approach to build supervised
  classification based predictive models for anti-tubercular agents from
  publicly available bioassay datasets for in-vitro screens for Mtb inhibitors.

- We have generated classification models for anti-tubercular agents with four
  commonly used state-of-the-art classifiers i.e. Naïve Bayes, Random Forest,
  J48 and SMO
 
* [ ] Ratnatunga2020 - The Rise of Non-Tuberculosis Mycobacterial Lung Disease
** Notes
- Survey paper for NTM
- Can be used for background context
** FileName
- Ratnatunga2020_RiseOfNTMLungDisease.pdf
** Abstract
- These lesser known “cousins” of Mycobacterium tuberculosis (TB) were once
  thought to be harmless environmental saprophytics and only dangerous to
  individuals with defective lung structure or the immunosuppressed.

- NTM have become extremely antibiotic resistant, and now have been found to be
  internationally dispersed through person-to-person contact.
 
** Conclusion
* WAIT Romero2020 - Decision tree machine learning applied to bovine tuberculosis risk factors to aid disease control decision making
** Notes
- Can use other algorithms for improving the accuracy i.e. XgBoost

- Uses Decision Tree Classifier to segregate the areas into low, mid, high risk

- Code is not provided

- Ask LJMU staff for help in this
** FileName
- Romero2020_DecisionTree.pdf
** Abstract
- Identifying and understanding the risk factors for endemic bovine tuberculosis
  (TB) in cattle herds is critical for the control of this disease. Exploratory
  machine learning techniques can uncover complex non-linear relation- ships and
  interactions within disease causation webs, and enhance our knowledge of TB
  risk factors and how they are interrelated.

-  The best classification tree models informed multivariable binomial logistic
  regression models in each area, adding statistical inference outputs. These
  two approaches showed similar predictive performance although there were some
  disparities regarding what constituted high-risk predictors.

- Decision tree machine learning approaches can identify risk factors from webs
  of causation: information which may then be used to inform decision making for
  disease control purposes.
 
** Conclusion
** Supplementary
*** Romero2020_DecisionTree_Corrigendum.pdf
* STRT Sauer2018 - Feature selection and prediction of treatment failure in tuberculosis
** Notes
- Code is available
  https://github.com/biosharp-dotnet/niaid_TB

- The data is sourced from dedicated NIH website
  https://tbportals.niaid.nih.gov/

- Can use XgBoost and/or H20

- Can add the data from other sources as well
** FileName
- Sauer2018_FeatureSelection.pdf
** Abstract
- On a multi-country dataset managed by the National Institute of Allergy and
  Infectious Diseases we applied various machine learning techniques to
  identify factors statistically associated with treatment failure and to
  predict treatment failure based on baseline demographic and clinical
  characteristics alone.
 
** Conclusion 
* [-] Schiff2018 - Clinical relevance of non-tuberculous mycobacteria isolated from respiratory specimens: seven year experience in a UK hospital
** Notes
- Survey report

- Can be used for background context
** FileName
- Schiff2018_ClinicalRelevanceOfNTM.pdf
** Abstract
** Conclusion
* Genome-wide Analysis of MDR and XDR Tuberculosis from Belarus: Machine-learning Approach
** FileName
- Sergeev2016_GenomeWide.pdf
** Notes
** Abstract
** Conclusion
* Vizcaino2010_ComputatationalPrediction.pdf
** FileName
** Notes
** Abstract
** Conclusion
* Waman2019_MycobacterialGenomics.pdf
** FileName
** Notes
** Abstract
** Conclusion
* Wang2020_ADeepLearningBasedMethod.pdf
** FileName
** Notes
** Abstract
** Conclusion
* Weiner2017_HighThroughput.pdf
** FileName
** Notes
** Abstract
** Conclusion
* Wilder2019_ImprovingTuberculosis.pdf
** FileName
** Notes
** Abstract
** Conclusion
* Yang2017_MachineLearning.pdf
** FileName
** Notes
** Abstract
** Conclusion
* Yang2019_DeepAMRForPredicting.pdf
** FileName
** Notes
** Abstract
** Conclusion
* Zhang2020_AnIntegratedMLApproach.pdf
** FileName
** Notes
** Abstract
** Conclusion
